name: Deploy to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup SSH Key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Debugging: Check if SSH Agent is working
      - name: Check SSH Agent
        run: |
          echo $SSH_AUTH_SOCK
          ssh-add -l

      # Deploy to Compute Engine
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no c183b4ky4122@34.128.71.208 << 'EOF'
          cd /home/c183b4ky4122/mid-project-cloud
          git pull origin main
          npm install # Opsional, untuk proyek Node.js
          sudo systemctl restart nginx
          EOF
